name: build-app
on: [push]
jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses:  actions/setup-go@v2
        with:
          go-version: '^1.16.0'
      - run: |
          sudo apt-get update
          sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev
      - run: go build
      - uses: actions/upload-artifact@v2
        with:
          name: linux-go-ffmpeg-ui
          path: go-ffmpeg-ui